// All cvmCode and cnpj values below were verified against the CVM Cias Abertas
// Informação Cadastral registry (cad_cia_aberta.csv) on 2026-05-07.
// Source: https://dados.cvm.gov.br/dados/CIA_ABERTA/CAD/DADOS/cad_cia_aberta.csv
import type { CvmCompany } from "./types";

const CVM_COMPANY_MAP: Record<string, CvmCompany> = {

  // ── Petróleo, Gás e Biocombustíveis ──────────────────────────────────────────
  PETR4: {
    ticker: "PETR4",
    tradingName: "PETROBRAS",
    companyName: "Petróleo Brasileiro S.A. — Petrobras",
    cvmCode: "9512",
    cnpj: "33.000.167/0001-01",
    sector: "Petróleo, Gás e Biocombustíveis",
    hasCvmMapping: true,
  },
  PETR3: {
    ticker: "PETR3",
    tradingName: "PETROBRAS",
    companyName: "Petróleo Brasileiro S.A. — Petrobras",
    cvmCode: "9512",
    cnpj: "33.000.167/0001-01",
    sector: "Petróleo, Gás e Biocombustíveis",
    hasCvmMapping: true,
  },
  PRIO3: {
    ticker: "PRIO3",
    tradingName: "PRIO",
    companyName: "PRIO S.A.",
    cvmCode: "22187",
    cnpj: "10.629.105/0001-68",
    sector: "Petróleo, Gás e Biocombustíveis",
    hasCvmMapping: true,
  },
  VBBR3: {
    ticker: "VBBR3",
    tradingName: "VIBRA",
    companyName: "Vibra Energia S.A.",
    cvmCode: "24295",
    cnpj: "34.274.233/0001-02",
    sector: "Petróleo, Gás e Biocombustíveis",
    hasCvmMapping: true,
  },
  RAIZ4: {
    ticker: "RAIZ4",
    tradingName: "RAÍZEN",
    // Legal name in CVM registry: RAÍZEN S.A.
    companyName: "Raízen S.A.",
    cvmCode: "25917",
    cnpj: "33.453.598/0001-23",
    sector: "Petróleo, Gás e Biocombustíveis",
    hasCvmMapping: true,
  },

  // ── Mineração e Siderurgia ────────────────────────────────────────────────────
  VALE3: {
    ticker: "VALE3",
    tradingName: "VALE",
    companyName: "Vale S.A.",
    cvmCode: "4170",
    cnpj: "33.592.510/0001-54",
    sector: "Materiais Básicos",
    hasCvmMapping: true,
  },
  GGBR4: {
    ticker: "GGBR4",
    tradingName: "GERDAU PN",
    companyName: "Gerdau S.A.",
    cvmCode: "3980",
    cnpj: "33.611.500/0001-19",
    sector: "Siderurgia",
    hasCvmMapping: true,
  },
  GGBR3: {
    ticker: "GGBR3",
    tradingName: "GERDAU ON",
    companyName: "Gerdau S.A.",
    cvmCode: "3980",
    cnpj: "33.611.500/0001-19",
    sector: "Siderurgia",
    hasCvmMapping: true,
  },
  CSNA3: {
    ticker: "CSNA3",
    tradingName: "CSN",
    // Registry: CIA SIDERURGICA NACIONAL
    companyName: "Companhia Siderúrgica Nacional",
    cvmCode: "4030",
    cnpj: "33.042.730/0001-04",
    sector: "Siderurgia",
    hasCvmMapping: true,
  },

  // ── Papel e Celulose ──────────────────────────────────────────────────────────
  SUZB3: {
    ticker: "SUZB3",
    tradingName: "SUZANO S.A.",
    companyName: "Suzano S.A.",
    cvmCode: "13986",
    cnpj: "16.404.287/0001-55",
    sector: "Materiais Básicos",
    hasCvmMapping: true,
  },
  KLBN11: {
    ticker: "KLBN11",
    tradingName: "KLABIN",
    companyName: "Klabin S.A.",
    cvmCode: "12653",
    cnpj: "89.637.490/0001-45",
    sector: "Papel e Celulose",
    hasCvmMapping: true,
  },

  // ── Bens de Capital ───────────────────────────────────────────────────────────
  WEGE3: {
    ticker: "WEGE3",
    tradingName: "WEG",
    companyName: "WEG S.A.",
    cvmCode: "5410",
    cnpj: "84.429.695/0001-11",
    sector: "Bens Industriais",
    hasCvmMapping: true,
  },
  EMBR3: {
    ticker: "EMBR3",
    tradingName: "EMBRAER",
    companyName: "Embraer S.A.",
    cvmCode: "20087",
    cnpj: "07.689.002/0001-89",
    sector: "Bens de Capital",
    hasCvmMapping: true,
  },
  TUPY3: {
    ticker: "TUPY3",
    tradingName: "TUPY",
    // Registry: TUPY SA
    companyName: "Tupy S.A.",
    cvmCode: "6343",
    cnpj: "84.683.374/0001-49",
    sector: "Bens de Capital",
    hasCvmMapping: true,
  },
  FRAS3: {
    ticker: "FRAS3",
    tradingName: "FRASLE",
    // Registry: FRASLE MOBILITY S.A.
    companyName: "Frasle Mobility S.A.",
    cvmCode: "6211",
    cnpj: "88.610.126/0001-29",
    sector: "Bens de Capital",
    hasCvmMapping: true,
  },

  // ── Energia Elétrica ──────────────────────────────────────────────────────────
  EGIE3: {
    ticker: "EGIE3",
    tradingName: "ENGIE BRASIL",
    companyName: "Engie Brasil Energia S.A.",
    cvmCode: "17329",
    cnpj: "02.474.103/0001-19",
    sector: "Utilidade Pública",
    hasCvmMapping: true,
  },
  CPFE3: {
    ticker: "CPFE3",
    tradingName: "CPFL ENERGIA",
    companyName: "CPFL Energia S.A.",
    cvmCode: "18660",
    cnpj: "02.429.144/0001-93",
    sector: "Utilidade Pública",
    hasCvmMapping: true,
  },
  // The CVM registry (as of 2026-05-07) lists this entity under "AXIA ENERGIA S.A."
  // (the legal name adopted after Eletrobras's privatization in 2022).
  // The CNPJ 00.001.180/0001-26 and CVM code 2437 are verified against the registry.
  // The B3 ticker ELET3 continues to trade under the Eletrobras brand.
  ELET3: {
    ticker: "ELET3",
    tradingName: "ELETROBRAS",
    companyName: "Centrais Elétricas Brasileiras S.A. — Eletrobras",
    cvmCode: "2437",
    cnpj: "00.001.180/0001-26",
    sector: "Utilidade Pública",
    hasCvmMapping: true,
  },
  EQTL3: {
    ticker: "EQTL3",
    tradingName: "EQUATORIAL",
    companyName: "Equatorial Energia S.A.",
    cvmCode: "20010",
    cnpj: "03.220.438/0001-73",
    sector: "Utilidade Pública",
    hasCvmMapping: true,
  },
  ENEV3: {
    ticker: "ENEV3",
    tradingName: "ENEVA",
    // Registry: ENEVA S.A. (formerly MPX Energia S.A.)
    companyName: "Eneva S.A.",
    cvmCode: "21237",
    cnpj: "04.423.567/0001-21",
    sector: "Energia Elétrica",
    hasCvmMapping: true,
  },
  CMIG4: {
    ticker: "CMIG4",
    tradingName: "CEMIG PN",
    // Registry: CIA ENERG MINAS GERAIS - CEMIG
    companyName: "Companhia Energética de Minas Gerais — Cemig",
    cvmCode: "2453",
    cnpj: "17.155.730/0001-64",
    sector: "Energia Elétrica",
    hasCvmMapping: true,
  },
  CMIG3: {
    ticker: "CMIG3",
    tradingName: "CEMIG ON",
    companyName: "Companhia Energética de Minas Gerais — Cemig",
    cvmCode: "2453",
    cnpj: "17.155.730/0001-64",
    sector: "Energia Elétrica",
    hasCvmMapping: true,
  },
  CPLE6: {
    ticker: "CPLE6",
    tradingName: "COPEL PNB",
    // Registry: COMPANHIA PARANAENSE DE ENERGIA COPEL
    companyName: "Companhia Paranaense de Energia — Copel",
    cvmCode: "14311",
    cnpj: "76.483.817/0001-20",
    sector: "Energia Elétrica",
    hasCvmMapping: true,
  },
  CPLE3: {
    ticker: "CPLE3",
    tradingName: "COPEL ON",
    companyName: "Companhia Paranaense de Energia — Copel",
    cvmCode: "14311",
    cnpj: "76.483.817/0001-20",
    sector: "Energia Elétrica",
    hasCvmMapping: true,
  },
  ALUP11: {
    ticker: "ALUP11",
    tradingName: "ALUPAR",
    // Registry: ALUPAR INVESTIMENTO S/A
    companyName: "Alupar Investimento S.A.",
    cvmCode: "21490",
    cnpj: "08.364.948/0001-38",
    sector: "Energia Elétrica",
    hasCvmMapping: true,
  },

  // ── Saneamento ────────────────────────────────────────────────────────────────
  SBSP3: {
    ticker: "SBSP3",
    tradingName: "SABESP",
    // Registry: CIA SANEAMENTO BÁSICO ESTADO SÃO PAULO
    companyName: "Companhia de Saneamento Básico do Estado de São Paulo — Sabesp",
    cvmCode: "14443",
    cnpj: "43.776.517/0001-80",
    sector: "Saneamento",
    hasCvmMapping: true,
  },

  // ── Telecomunicações ──────────────────────────────────────────────────────────
  VIVT3: {
    ticker: "VIVT3",
    tradingName: "TELEF BRASIL",
    companyName: "Telefônica Brasil S.A.",
    cvmCode: "17671",
    cnpj: "02.558.157/0001-62",
    sector: "Comunicações",
    hasCvmMapping: true,
  },
  TIMS3: {
    ticker: "TIMS3",
    tradingName: "TIM",
    // Registry: TIM S.A. (formerly TIM Participações S.A.)
    companyName: "TIM S.A.",
    cvmCode: "24929",
    cnpj: "02.421.421/0001-11",
    sector: "Telecomunicações",
    hasCvmMapping: true,
  },

  // ── Bebidas ───────────────────────────────────────────────────────────────────
  ABEV3: {
    ticker: "ABEV3",
    tradingName: "AMBEV S/A",
    companyName: "Ambev S.A.",
    cvmCode: "23264",
    cnpj: "07.526.557/0001-00",
    sector: "Consumo Não Cíclico",
    hasCvmMapping: true,
  },

  // ── Transporte e Logística ────────────────────────────────────────────────────
  RAIL3: {
    ticker: "RAIL3",
    tradingName: "RUMO",
    // Registry: RUMO S.A. (previously ALL - América Latina Logística S.A.)
    companyName: "Rumo S.A.",
    cvmCode: "17450",
    cnpj: "02.387.241/0001-60",
    sector: "Transporte",
    hasCvmMapping: true,
  },
  RENT3: {
    ticker: "RENT3",
    tradingName: "LOCALIZA",
    // Registry: LOCALIZA RENT A CAR SA
    companyName: "Localiza Rent a Car S.A.",
    cvmCode: "19739",
    cnpj: "16.670.085/0001-55",
    sector: "Transporte",
    hasCvmMapping: true,
  },

  // ── Varejo ────────────────────────────────────────────────────────────────────
  LREN3: {
    ticker: "LREN3",
    tradingName: "RENNER",
    // Registry: LOJAS RENNER SA
    companyName: "Lojas Renner S.A.",
    cvmCode: "8133",
    cnpj: "92.754.738/0001-62",
    sector: "Varejo",
    hasCvmMapping: true,
  },
  ASAI3: {
    ticker: "ASAI3",
    tradingName: "ASSAÍ ATACADISTA",
    // CVM legal entity: SENDAS DISTRIBUIDORA S.A. — operates the Assaí Atacadista brand
    // Spun off from GPA (PCAR3) in 2021 and listed separately as ASAI3.
    companyName: "Sendas Distribuidora S.A.",
    cvmCode: "25372",
    cnpj: "06.057.223/0001-71",
    sector: "Varejo",
    hasCvmMapping: true,
  },

  // ── Saúde ─────────────────────────────────────────────────────────────────────
  RADL3: {
    ticker: "RADL3",
    tradingName: "RD SAÚDE",
    // Registry: RAIA DROGASIL S.A. (merged entity of Droga Raia + Drogasil, 2011)
    companyName: "Raia Drogasil S.A.",
    cvmCode: "5258",
    cnpj: "61.585.865/0001-51",
    sector: "Saúde",
    hasCvmMapping: true,
  },
  HYPE3: {
    ticker: "HYPE3",
    tradingName: "HYPERA PHARMA",
    // Registry: HYPERA S/A (formerly Hypermarcas S.A.)
    companyName: "Hypera S.A.",
    cvmCode: "21431",
    cnpj: "02.932.074/0001-91",
    sector: "Saúde",
    hasCvmMapping: true,
  },

  // ── Energia Elétrica ──────────────────────────────────────────────────────────
  TRPL4: {
    ticker: "TRPL4",
    tradingName: "ISA CTEEP",
    // Renamed ISA Energia Brasil S.A. after ISA Group acquisition; ticker TRPL4 unchanged.
    companyName: "ISA Energia Brasil S.A.",
    cvmCode: "18376",
    cnpj: "02.998.611/0001-04",
    sector: "Energia Elétrica",
    hasCvmMapping: true,
  },
  ENBR3: {
    ticker: "ENBR3",
    tradingName: "ENERGIAS BR",
    companyName: "EDP Energias do Brasil S.A.",
    cvmCode: "19763",
    cnpj: "03.983.431/0001-03",
    sector: "Energia Elétrica",
    hasCvmMapping: true,
  },
  CESP6: {
    ticker: "CESP6",
    tradingName: "CESP",
    companyName: "CESP — Companhia Energética de São Paulo",
    cvmCode: "2577",
    cnpj: "60.933.603/0001-78",
    sector: "Energia Elétrica",
    hasCvmMapping: true,
  },
  ENGI11: {
    ticker: "ENGI11",
    tradingName: "ENERGISA",
    companyName: "Energisa S.A.",
    cvmCode: "15253",
    cnpj: "00.864.214/0001-06",
    sector: "Energia Elétrica",
    hasCvmMapping: true,
  },
  TAEE11: {
    ticker: "TAEE11",
    tradingName: "TAESA",
    companyName: "Transmissora Aliança de Energia Elétrica S.A.",
    cvmCode: "20257",
    cnpj: "07.859.971/0001-30",
    sector: "Energia Elétrica",
    hasCvmMapping: true,
  },
  AURE3: {
    ticker: "AURE3",
    tradingName: "AUREN",
    companyName: "Auren Energia S.A.",
    cvmCode: "26620",
    cnpj: "28.594.234/0001-23",
    sector: "Energia Elétrica",
    hasCvmMapping: true,
  },
  ELET6: {
    ticker: "ELET6",
    tradingName: "ELETROBRAS",
    companyName: "Centrais Elétricas Brasileiras S.A. — Eletrobras",
    cvmCode: "2437",
    cnpj: "00.001.180/0001-26",
    sector: "Energia Elétrica",
    hasCvmMapping: true,
  },

  // ── Saneamento ────────────────────────────────────────────────────────────────
  CSMG3: {
    ticker: "CSMG3",
    tradingName: "COPASA",
    companyName: "Companhia de Saneamento de Minas Gerais — Copasa MG",
    cvmCode: "19445",
    cnpj: "17.281.106/0001-03",
    sector: "Saneamento",
    hasCvmMapping: true,
  },
  SAPR11: {
    ticker: "SAPR11",
    tradingName: "SANEPAR",
    companyName: "Companhia de Saneamento do Paraná — Sanepar",
    cvmCode: "18627",
    cnpj: "76.484.013/0001-45",
    sector: "Saneamento",
    hasCvmMapping: true,
  },

  // ── Gás ───────────────────────────────────────────────────────────────────────
  CGAS3: {
    ticker: "CGAS3",
    tradingName: "COMGÁS",
    companyName: "Companhia de Gás de São Paulo — Comgás",
    cvmCode: "15636",
    cnpj: "61.856.571/0001-17",
    sector: "Petróleo, Gás e Biocombustíveis",
    hasCvmMapping: true,
  },

  // ── Bens de Capital ───────────────────────────────────────────────────────────
  MYPK3: {
    ticker: "MYPK3",
    tradingName: "IOCHP-MAXION",
    companyName: "Iochpe-Maxion S.A.",
    cvmCode: "11932",
    cnpj: "61.156.113/0001-75",
    sector: "Bens Industriais",
    hasCvmMapping: true,
  },
  ROMI3: {
    ticker: "ROMI3",
    tradingName: "ROMI",
    companyName: "Romi S.A.",
    cvmCode: "7510",
    cnpj: "56.720.428/0001-63",
    sector: "Bens Industriais",
    hasCvmMapping: true,
  },
  RAPT4: {
    ticker: "RAPT4",
    tradingName: "RANDON PART",
    // Legal name changed to Randoncorp S.A. after corporate reorganisation.
    companyName: "Randoncorp S.A.",
    cvmCode: "14109",
    cnpj: "89.086.144/0001-16",
    sector: "Bens Industriais",
    hasCvmMapping: true,
  },
  POMO4: {
    ticker: "POMO4",
    tradingName: "MARCOPOLO",
    companyName: "Marcopolo S.A.",
    cvmCode: "8451",
    cnpj: "88.611.835/0001-29",
    sector: "Bens Industriais",
    hasCvmMapping: true,
  },
  KEPL3: {
    ticker: "KEPL3",
    tradingName: "KEPLER WEBER",
    companyName: "Kepler Weber S.A.",
    cvmCode: "7870",
    cnpj: "91.983.056/0001-69",
    sector: "Bens Industriais",
    hasCvmMapping: true,
  },
  TASA4: {
    ticker: "TASA4",
    tradingName: "TAURUS ARMAS",
    companyName: "Taurus Armas S.A.",
    cvmCode: "6173",
    cnpj: "92.781.335/0001-02",
    sector: "Bens de Capital",
    hasCvmMapping: true,
  },
  LEVE3: {
    ticker: "LEVE3",
    tradingName: "METAL LEVE",
    // Now Mahle Metal Leve S.A. following Mahle Group acquisition.
    companyName: "Mahle Metal Leve S.A.",
    cvmCode: "8575",
    cnpj: "60.476.884/0001-87",
    sector: "Bens Industriais",
    hasCvmMapping: true,
  },

  // ── Siderurgia e Metalurgia ────────────────────────────────────────────────────
  USIM5: {
    ticker: "USIM5",
    tradingName: "USIMINAS",
    companyName: "Usinas Siderúrgicas de Minas Gerais S.A. — Usiminas",
    cvmCode: "14320",
    cnpj: "60.894.730/0001-05",
    sector: "Materiais Básicos",
    hasCvmMapping: true,
  },
  GOAU4: {
    ticker: "GOAU4",
    tradingName: "GERDAU MET",
    companyName: "Metalúrgica Gerdau S.A.",
    cvmCode: "8656",
    cnpj: "92.690.783/0001-09",
    sector: "Materiais Básicos",
    hasCvmMapping: true,
  },
  FESA4: {
    ticker: "FESA4",
    tradingName: "FERBASA",
    companyName: "Cia de Ferro Ligas da Bahia — Ferbasa",
    cvmCode: "3069",
    cnpj: "15.141.799/0001-03",
    sector: "Materiais Básicos",
    hasCvmMapping: true,
  },

  // ── Químicos ──────────────────────────────────────────────────────────────────
  BRKM5: {
    ticker: "BRKM5",
    tradingName: "BRASKEM",
    companyName: "Braskem S.A.",
    cvmCode: "4820",
    cnpj: "42.150.391/0001-70",
    sector: "Materiais Básicos",
    hasCvmMapping: true,
  },
  UNIP6: {
    ticker: "UNIP6",
    tradingName: "UNIPAR",
    companyName: "Unipar Carbocloro S.A.",
    cvmCode: "11592",
    cnpj: "33.958.695/0001-78",
    sector: "Materiais Básicos",
    hasCvmMapping: true,
  },

  // ── Papel e Celulose ──────────────────────────────────────────────────────────
  DXCO3: {
    ticker: "DXCO3",
    tradingName: "DEXCO",
    companyName: "Dexco S.A.",
    cvmCode: "21091",
    cnpj: "97.837.181/0001-47",
    sector: "Materiais Básicos",
    hasCvmMapping: true,
  },

  // ── Mineração ─────────────────────────────────────────────────────────────────
  CMIN3: {
    ticker: "CMIN3",
    tradingName: "CSN MINERAÇÃO",
    companyName: "CSN Mineração S.A.",
    cvmCode: "25585",
    cnpj: "08.902.291/0001-15",
    sector: "Materiais Básicos",
    hasCvmMapping: true,
  },

  // ── Alimentos e Bebidas ───────────────────────────────────────────────────────
  BRFS3: {
    ticker: "BRFS3",
    tradingName: "BRF SA",
    companyName: "BRF S.A.",
    cvmCode: "16292",
    cnpj: "01.838.723/0001-27",
    sector: "Consumo não Cíclico",
    hasCvmMapping: true,
  },
  JBSS3: {
    ticker: "JBSS3",
    tradingName: "JBS",
    companyName: "JBS S.A.",
    cvmCode: "20575",
    cnpj: "02.916.265/0001-60",
    sector: "Consumo não Cíclico",
    hasCvmMapping: true,
  },
  MRFG3: {
    ticker: "MRFG3",
    tradingName: "MARFRIG",
    companyName: "Marfrig Global Foods S.A.",
    cvmCode: "20788",
    cnpj: "03.853.896/0001-40",
    sector: "Consumo não Cíclico",
    hasCvmMapping: true,
  },
  BEEF3: {
    ticker: "BEEF3",
    tradingName: "MINERVA",
    companyName: "Minerva S.A.",
    cvmCode: "20931",
    cnpj: "67.620.377/0001-14",
    sector: "Consumo não Cíclico",
    hasCvmMapping: true,
  },
  SMTO3: {
    ticker: "SMTO3",
    tradingName: "SÃO MARTINHO",
    companyName: "São Martinho S.A.",
    cvmCode: "20516",
    cnpj: "51.466.860/0001-56",
    sector: "Consumo não Cíclico",
    hasCvmMapping: true,
  },
  MDIA3: {
    ticker: "MDIA3",
    tradingName: "M.DIASBRANCO",
    companyName: "M. Dias Branco S.A. Ind. e Com. de Alimentos",
    cvmCode: "20338",
    cnpj: "07.206.816/0001-15",
    sector: "Consumo não Cíclico",
    hasCvmMapping: true,
  },
  SLCE3: {
    ticker: "SLCE3",
    tradingName: "SLC AGRÍCOLA",
    companyName: "SLC Agrícola S.A.",
    cvmCode: "20745",
    cnpj: "89.096.457/0001-55",
    sector: "Consumo não Cíclico",
    hasCvmMapping: true,
  },
  AGRO3: {
    ticker: "AGRO3",
    tradingName: "BRASILAGRO",
    companyName: "BrasilAgro — Cia Brasileira de Propriedades Agrícolas",
    cvmCode: "20036",
    cnpj: "07.628.528/0001-59",
    sector: "Consumo não Cíclico",
    hasCvmMapping: true,
  },

  // ── Transporte e Logística ────────────────────────────────────────────────────
  AZUL4: {
    ticker: "AZUL4",
    tradingName: "AZUL",
    companyName: "Azul S.A.",
    cvmCode: "24112",
    cnpj: "09.305.994/0001-29",
    sector: "Transporte",
    hasCvmMapping: true,
  },
  // GOLL4 removed: GOL Linhas Aéreas entity (CVM 19569) status = CANCELADA in registry.
  STBP3: {
    ticker: "STBP3",
    tradingName: "SANTOS BRASIL",
    companyName: "Santos Brasil Participações S.A.",
    cvmCode: "17892",
    cnpj: "02.762.121/0001-04",
    sector: "Transporte",
    hasCvmMapping: true,
  },
  TGMA3: {
    ticker: "TGMA3",
    tradingName: "TEGMA",
    companyName: "Tegma Gestão Logística S.A.",
    cvmCode: "20800",
    cnpj: "02.351.144/0001-18",
    sector: "Transporte",
    hasCvmMapping: true,
  },
  MOVI3: {
    ticker: "MOVI3",
    tradingName: "MOVIDA",
    companyName: "Movida Participações S.A.",
    cvmCode: "23825",
    cnpj: "21.314.559/0001-66",
    sector: "Transporte",
    hasCvmMapping: true,
  },
  SIMH3: {
    ticker: "SIMH3",
    tradingName: "SIMPAR",
    companyName: "Simpar S.A.",
    cvmCode: "25003",
    cnpj: "07.415.333/0001-20",
    sector: "Transporte",
    hasCvmMapping: true,
  },

  // ── Varejo ────────────────────────────────────────────────────────────────────
  MGLU3: {
    ticker: "MGLU3",
    tradingName: "MAGAZ LUIZA",
    companyName: "Magazine Luiza S.A.",
    cvmCode: "22470",
    cnpj: "47.960.950/0001-21",
    sector: "Consumo Cíclico",
    hasCvmMapping: true,
  },
  PCAR3: {
    ticker: "PCAR3",
    tradingName: "P.AÇÚCAR-CBD",
    companyName: "Companhia Brasileira de Distribuição",
    cvmCode: "14826",
    cnpj: "47.508.411/0001-56",
    sector: "Consumo não Cíclico",
    hasCvmMapping: true,
  },
  // CRFB3 removed: Atacadão S.A. (CVM 24171) status = CANCELADA; no successor ATIVO entity found.
  ARZZ3: {
    ticker: "ARZZ3",
    tradingName: "AREZZO CO",
    // After Arezzo + Grupo Soma merger (2023), legal entity became AZZAS 2154 S.A.
    companyName: "AZZAS 2154 S.A.",
    cvmCode: "22349",
    cnpj: "16.590.234/0001-76",
    sector: "Consumo Cíclico",
    hasCvmMapping: true,
  },
  GRND3: {
    ticker: "GRND3",
    tradingName: "GRENDENE",
    companyName: "Grendene S.A.",
    cvmCode: "19615",
    cnpj: "89.850.341/0001-60",
    sector: "Consumo Cíclico",
    hasCvmMapping: true,
  },
  ALPA4: {
    ticker: "ALPA4",
    tradingName: "ALPARGATAS",
    companyName: "Alpargatas S.A.",
    cvmCode: "10456",
    cnpj: "61.079.117/0001-05",
    sector: "Consumo Cíclico",
    hasCvmMapping: true,
  },
  VULC3: {
    ticker: "VULC3",
    tradingName: "VULCABRAS",
    companyName: "Vulcabras S.A.",
    cvmCode: "11762",
    cnpj: "50.926.955/0001-42",
    sector: "Consumo Cíclico",
    hasCvmMapping: true,
  },
  // SOMA3 removed: Grupo de Moda Soma S.A. (CVM 25011) status = CANCELADA; merged into AZZAS 2154 (ARZZ3).


  // ── Saúde (expansão) ──────────────────────────────────────────────────────────
  FLRY3: {
    ticker: "FLRY3",
    tradingName: "FLEURY",
    companyName: "Fleury S.A.",
    cvmCode: "21881",
    cnpj: "60.840.055/0001-31",
    sector: "Saúde",
    hasCvmMapping: true,
  },
  ODPV3: {
    ticker: "ODPV3",
    tradingName: "ODONTOPREV",
    companyName: "Bradsaúde S.A.",
    cvmCode: "20125",
    cnpj: "58.119.199/0001-51",
    sector: "Saúde",
    hasCvmMapping: true,
  },
  RDOR3: {
    ticker: "RDOR3",
    tradingName: "REDE D'OR",
    companyName: "Rede D'Or São Luiz S.A.",
    cvmCode: "24821",
    cnpj: "06.047.087/0001-39",
    sector: "Saúde",
    hasCvmMapping: true,
  },
  HAPV3: {
    ticker: "HAPV3",
    tradingName: "HAPVIDA",
    companyName: "Hapvida Participações e Investimentos S.A.",
    cvmCode: "24392",
    cnpj: "05.197.443/0001-38",
    sector: "Saúde",
    hasCvmMapping: true,
  },
  QUAL3: {
    ticker: "QUAL3",
    tradingName: "QUALICORP",
    companyName: "Qualicorp Consultoria e Corretora de Seguros S.A.",
    cvmCode: "22497",
    cnpj: "11.992.680/0001-93",
    sector: "Saúde",
    hasCvmMapping: true,
  },

  // ── Educação ──────────────────────────────────────────────────────────────────
  COGN3: {
    ticker: "COGN3",
    tradingName: "COGNA ON",
    companyName: "Cogna Educação S.A.",
    cvmCode: "17973",
    cnpj: "02.800.026/0001-40",
    sector: "Consumo Cíclico",
    hasCvmMapping: true,
  },
  YDUQ3: {
    ticker: "YDUQ3",
    tradingName: "YDUQS PART",
    companyName: "Yduqs Participações S.A.",
    cvmCode: "21016",
    cnpj: "08.807.432/0001-10",
    sector: "Consumo Cíclico",
    hasCvmMapping: true,
  },
  SEER3: {
    ticker: "SEER3",
    tradingName: "SER EDUCA",
    companyName: "Ser Educacional S.A.",
    cvmCode: "23221",
    cnpj: "04.986.320/0001-13",
    sector: "Consumo Cíclico",
    hasCvmMapping: true,
  },
  CSED3: {
    ticker: "CSED3",
    tradingName: "CRUZEIRO ED",
    companyName: "Cruzeiro do Sul Educacional S.A.",
    cvmCode: "25526",
    cnpj: "62.984.091/0001-02",
    sector: "Consumo Cíclico",
    hasCvmMapping: true,
  },
  ANIM3: {
    ticker: "ANIM3",
    tradingName: "ANIMA",
    companyName: "Ânima Holding S.A.",
    cvmCode: "23248",
    cnpj: "09.288.252/0001-32",
    sector: "Consumo Cíclico",
    hasCvmMapping: true,
  },

  // ── Tecnologia ────────────────────────────────────────────────────────────────
  TOTS3: {
    ticker: "TOTS3",
    tradingName: "TOTVS",
    companyName: "TOTVS S.A.",
    cvmCode: "19992",
    cnpj: "53.113.791/0001-22",
    sector: "Tecnologia da Informação",
    hasCvmMapping: true,
  },
  LWSA3: {
    ticker: "LWSA3",
    tradingName: "LWSA",
    companyName: "LWSA S.A.",
    cvmCode: "24910",
    cnpj: "02.351.877/0001-52",
    sector: "Tecnologia da Informação",
    hasCvmMapping: true,
  },
  INTB3: {
    ticker: "INTB3",
    tradingName: "INTELBRAS",
    companyName: "Intelbras S.A. Ind. de Telecomunicação Eletrônica Brasileira",
    cvmCode: "25453",
    cnpj: "82.901.000/0001-27",
    sector: "Tecnologia da Informação",
    hasCvmMapping: true,
  },

  // ── Construção Civil ──────────────────────────────────────────────────────────
  CYRE3: {
    ticker: "CYRE3",
    tradingName: "CYRELA REALT",
    companyName: "Cyrela Brazil Realty S.A. Empreendimentos e Participações",
    cvmCode: "14460",
    cnpj: "73.178.600/0001-18",
    sector: "Consumo Cíclico",
    hasCvmMapping: true,
  },
  MRVE3: {
    ticker: "MRVE3",
    tradingName: "MRV",
    companyName: "MRV Engenharia e Participações S.A.",
    cvmCode: "20915",
    cnpj: "08.343.492/0001-20",
    sector: "Consumo Cíclico",
    hasCvmMapping: true,
  },
  DIRR3: {
    ticker: "DIRR3",
    tradingName: "DIRECIONAL",
    companyName: "Direcional Engenharia S.A.",
    cvmCode: "21350",
    cnpj: "16.614.075/0001-00",
    sector: "Consumo Cíclico",
    hasCvmMapping: true,
  },
  TEND3: {
    ticker: "TEND3",
    tradingName: "TENDA",
    companyName: "Construtora Tenda S.A.",
    cvmCode: "21148",
    cnpj: "71.476.527/0001-35",
    sector: "Consumo Cíclico",
    hasCvmMapping: true,
  },
  EVEN3: {
    ticker: "EVEN3",
    tradingName: "EVEN",
    companyName: "Even Construtora e Incorporadora S.A.",
    cvmCode: "20524",
    cnpj: "43.470.988/0001-65",
    sector: "Consumo Cíclico",
    hasCvmMapping: true,
  },
  GFSA3: {
    ticker: "GFSA3",
    tradingName: "GAFISA",
    companyName: "Gafisa S.A.",
    cvmCode: "16101",
    cnpj: "01.545.826/0001-07",
    sector: "Consumo Cíclico",
    hasCvmMapping: true,
  },
  MTRE3: {
    ticker: "MTRE3",
    tradingName: "MITRE REALTY",
    companyName: "Mitre Realty Empreendimentos e Participações S.A.",
    cvmCode: "24902",
    cnpj: "07.882.930/0001-65",
    sector: "Consumo Cíclico",
    hasCvmMapping: true,
  },
  CURY3: {
    ticker: "CURY3",
    tradingName: "CURY CONSTRU",
    companyName: "Cury Construtora e Incorporadora S.A.",
    cvmCode: "25100",
    cnpj: "08.797.760/0001-83",
    sector: "Consumo Cíclico",
    hasCvmMapping: true,
  },

  // ── Imóveis Comerciais e Participações ────────────────────────────────────────
  MULT3: {
    ticker: "MULT3",
    tradingName: "MULTIPLAN",
    companyName: "Multiplan — Empreendimentos Imobiliários S.A.",
    cvmCode: "20982",
    cnpj: "07.816.890/0001-53",
    sector: "Consumo Cíclico",
    hasCvmMapping: true,
  },
  IGTI11: {
    ticker: "IGTI11",
    tradingName: "IGUATEMI S.A",
    companyName: "Iguatemi S.A.",
    cvmCode: "8672",
    cnpj: "60.543.816/0001-93",
    sector: "Consumo Cíclico",
    hasCvmMapping: true,
  },
  JHSF3: {
    ticker: "JHSF3",
    tradingName: "JHSF PART",
    companyName: "JHSF Participações S.A.",
    cvmCode: "20605",
    cnpj: "08.294.224/0001-65",
    sector: "Consumo Cíclico",
    hasCvmMapping: true,
  },
  // BRPR3 removed: BR Properties S.A. (CVM 19925) status CANCELADA in registry — no DFP data available

  // ── Serviços Diversos ─────────────────────────────────────────────────────────
  CVCB3: {
    ticker: "CVCB3",
    tradingName: "CVC BRASIL",
    companyName: "CVC Brasil Operadora e Agência de Viagens S.A.",
    cvmCode: "23310",
    cnpj: "10.760.260/0001-19",
    sector: "Consumo Cíclico",
    hasCvmMapping: true,
  },
  NTCO3: {
    ticker: "NTCO3",
    tradingName: "GRUPO NATURA",
    companyName: "Natura Cosméticos S.A.",
    cvmCode: "19550",
    cnpj: "71.673.990/0001-77",
    sector: "Consumo não Cíclico",
    hasCvmMapping: true,
  },
  UGPA3: {
    ticker: "UGPA3",
    tradingName: "ULTRAPAR",
    companyName: "Ultrapar Participações S.A.",
    cvmCode: "18465",
    cnpj: "33.256.439/0001-39",
    sector: "Petróleo, Gás e Biocombustíveis",
    hasCvmMapping: true,
  },
  CSAN3: {
    ticker: "CSAN3",
    tradingName: "COSAN",
    companyName: "Cosan S.A.",
    cvmCode: "19836",
    cnpj: "50.746.577/0001-15",
    sector: "Petróleo, Gás e Biocombustíveis",
    hasCvmMapping: true,
  },
};

export function getCvmCompanyByTicker(ticker: string): CvmCompany | null {
  return CVM_COMPANY_MAP[ticker.toUpperCase()] ?? null;
}

export { CVM_COMPANY_MAP };
